### ISSUE TITLE
Resource Bundle target is named "TvOSMoreButton-TvOSMoreButton"?

### ISSUE THREAD

**Issue by dcordero** [cgoldsby/TvOSMoreButton#12]
When integrating TvOSMoreButton into my project, I see that apart from "TvOSMoreButton" it creates an extra target called "TvOSMoreButton-TvOSMoreButton".

It also happens in the Example project in this repo:

<img width="566" alt="screen shot 2017-12-01 at 10 39 35" src="https://user-images.githubusercontent.com/2320840/33476921-09e6ca10-d684-11e7-9e9d-97f513314102.png">

**Comment by cgoldsby** [comment]
@dcordero Thanks for the info. The extra target is to create a resource bundle for localizations. So, I think the two targets is okay.

What doe surprise me is the naming convention **CocoaPods** is using `TVOSMoreButton-TvOSMoreButton`. I am going to keep this ticket open so I can investigate a little more.


<img width="881" alt="screen shot 2017-12-01 at 8 26 00 am" src="https://user-images.githubusercontent.com/3449816/33484700-6fd936ea-d671-11e7-9ab5-ab95b9fa015b.png">

<img width="670" alt="screen shot 2017-12-01 at 8 25 45 am" src="https://user-images.githubusercontent.com/3449816/33484691-6d5e8ad2-d671-11e7-8156-ab300a82155f.png">

**Comment by cgoldsby** [comment]
After a little research, the XCode target name is created using the [library name](https://github.com/CocoaPods/CocoaPods/blob/f6a7d53286ccbc4c5e419c33f0eb3dbc320af2be/lib/cocoapods/target.rb#L30) prepended to the [resource name](https://github.com/CocoaPods/CocoaPods/blob/f6a7d53286ccbc4c5e419c33f0eb3dbc320af2be/lib/cocoapods/target/pod_target.rb#L366). `TvOSMoreButton-TvOSMoreButton` matches the [spec](https://github.com/CocoaPods/CocoaPods/blob/da046a134e507ff0bd2584cef62963bf8894e760/spec/unit/target/pod_target_spec.rb#L67).

Since the [Podspec](https://github.com/cgoldsby/TvOSMoreButton/blob/84455e332e2108cff1e18bd1ce59ed1ca45caeac/TvOSMoreButton.podspec#L11) matches the [documentation](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles), I am going to close this ticket. Even though the Xcode Target name is a little repetitive and looks weird.
