### ISSUE TITLE
Unable to find a specification for `TvOSMoreButton (~> 1.3.0)`

### ISSUE THREAD

**Issue by NSExceptional** [cgoldsby/TvOSMoreButton#36]
Did you actually publish any versions to the Cocoapods trunk after 1.2.0?

**Comment by cgoldsby** [comment]
Hi, thank you so much for your interest in `TvOSMoreButton`, and I apologize for the very, very late reply. :bow: The last update with functionality changes was in 1.2.3.

Since then, there have been a few minor releases to fix Xcode warnings and support Swift Package Manager (SPM) but no functionality changes.

Today, I published v1.4.1, which contains the latest code changes from `main`.

More details can be found on the [Release page](https://github.com/cgoldsby/TvOSMoreButton/releases).
